server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Microservice2
          uri: http://localhost:8082/
          predicates:
            - Path=/service2/**